# Site settings
title: Sunan Fatima
email: fatima.sunan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Case studies and explorations in mathematical modeling with applications in systems biology and medicine.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
